apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer
  namespace: geo-infra
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: adminer.combaldieu.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oathkeeper-proxy-forward
                port:
                  number: 4455
  tls:
    - hosts:
        - adminer.combaldieu.fr
      secretName: adminer-tls