---
apiVersion: v1
kind: Namespace
metadata:
  name: geo-infra
  labels:
    name: geo-infra
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: geo-ory
  labels:
    name: geo-ory
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: geo-app
  labels:
    name: geo-app
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx